# <i>Data Cleaning</i>

### Importing libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

### 1. Reading the Data

In [2]:
df = pd.read_csv("cardio_train.csv")
df

      id;age;gender;height;weight;ap_hi;ap_lo;cholesterol;gluc;smoke;alco;active;cardio
0                  0;18393;2;168;62.0;110;80;1;1;0;0;1;0
1                  1;20228;1;156;85.0;140;90;3;1;0;0;1;1
2                  2;18857;1;165;64.0;130;70;3;1;0;0;0;1
3                 3;17623;2;169;82.0;150;100;1;1;0;0;1;1
4                  4;17474;1;156;56.0;100;60;1;1;0;0;0;0
...                                                  ...
69995          99993;19240;2;168;76.0;120;80;1;1;1;0;1;0
69996         99995;22601;1;158;126.0;140;90;2;2;0;0;1;1
69997         99996;19066;2;183;105.0;180;90;3;1;0;1;0;1
69998          99998;22431;1;163;72.0;135;80;1;2;0;0;0;1
69999          99999;20540;1;170;72.0;120;80;2;1;0;0;1;0

[70000 rows x 1 columns]

### 2. seprate with comma

In [3]:
df = pd.read_csv("cardio_train.csv", sep=';')
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

### 3.

In [4]:
df.tail()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

### 4-8. exploring data set

In [5]:
df.shape

(70000, 13)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [7]:
df.isnull().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [8]:
df.describe()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
count,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000
mean,49972.419900,19468.865814,1.349571,164.359229,74.205690,128.817286,96.630414,1.366871,1.226457,0.088129,0.053771,0.803729,0.499700
std,28851.302323,2467.251667,0.476838,8.210126,14.395757,154.011419,188.472530,0.680250,0.572270,0.283484,0.225568,0.397179,0.500003
min,0.000000,10798.000000,1.000000,55.000000,10.000000,-150.000000,-70.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,25006.750000,17664.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,50001.500000,19703.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,74889.250000,21327.000000,2.000000,170.000000,82.000000,140.000000,90.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,99999.000000,23713.000000,2.000000,250.000000,200.000000,16020.000000,11000.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
df.duplicated().sum()

0

### 9. Remove Duplicate

In [10]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

0

### 10. Remove Id column

In [11]:
df.drop(columns=['id'], inplace=True)
df.head()

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,17474,1,156,56.0,100,60,1,1,0,0,0,0

### 11. Age days into year

In [12]:
df['age'] = (df['age'] / 365).astype(int)
df.tail()

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
69995,52,2,168,76.0,120,80,1,1,1,0,1,0
69996,61,1,158,126.0,140,90,2,2,0,0,1,1
69997,52,2,183,105.0,180,90,3,1,0,1,0,1
69998,61,1,163,72.0,135,80,1,2,0,0,0,1
69999,56,1,170,72.0,120,80,2,1,0,0,1,0

### 12. Fix Dtatype

In [13]:
cat_cols = ['gender','cholesterol', 'gluc', 'smoke', 'alco', 'active', 'cardio']
for col in cat_cols:
    df[col] = df[col].astype('category')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          70000 non-null  int32
 1   gender       70000 non-null  category
 2   height       70000 non-null  int64
 3   weight       70000 non-null  float64
 4   ap_hi        70000 non-null  int64
 5   ap_lo        70000 non-null  int64
 6   cholesterol  70000 non-null  category
 7   gluc         70000 non-null  category
 8   smoke        70000 non-null  category
 9   alco         70000 non-null  category
 10  active       70000 non-null  category
 11  cardio       70000 non-null  category
dtypes: category(7), float64(1), int32(1), int64(3)
memory usage: 2.9 MB

### 13-14. Remove extreme outliers in height & weight

In [14]:
df = df[(df['height'] >= 120) & (df['height'] <= 220)]

In [15]:
df = df[(df['weight'] >= 30) & (df['weight'] <= 200)]

### 15. Filter out impossible & outliers blood pressure values

In [16]:
df = df[df['ap_hi'] >= df['ap_lo']]
df = df[(df['ap_hi'] > 0) & (df['ap_lo'] > 0)]
df = df[(df['ap_hi'] < 300) & (df['ap_lo'] < 200)]

### 16. Create BMI column

In [17]:
df['bmi'] = df['weight'] / ((df['height']/100)**2)
df.head()

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,bmi
0,50,2,168,62.0,110,80,1,1,0,0,1,0,21.967120
1,55,1,156,85.0,140,90,3,1,0,0,1,1,34.927679
2,51,1,165,64.0,130,70,3,1,0,0,0,1,23.507805
3,48,2,169,82.0,150,100,1,1,0,0,1,1,28.710479
4,47,1,156,56.0,100,60,1,1,0,0,0,0,23.011177

### 17. Unique Values

In [18]:
print(df['gender'].unique())
print(df['cholesterol'].unique())
print(df['gluc'].unique())
print(df['smoke'].unique())
print(df['alco'].unique())
print(df['active'].unique())
print(df['cardio'].unique())

[2, 1]
Categories (2, int64): [1, 2]
[1, 3, 2]
Categories (3, int64): [1, 2, 3]
[1, 2, 3]
Categories (3, int64): [1, 2, 3]
[0, 1]
Categories (2, int64): [0, 1]
[0, 1]
Categories (2, int64): [0, 1]
[1, 0]
Categories (2, int64): [0, 1]
[0, 1]
Categories (2, int64): [0, 1]

### 18. Remove height weight or bmi (Redudandunt)

In [19]:
df = df.drop(['height', 'weight'], axis=1)
df.head()

,age,gender,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,bmi
0,50,2,110,80,1,1,0,0,1,0,21.967120
1,55,1,140,90,3,1,0,0,1,1,34.927679
2,51,1,130,70,3,1,0,0,0,1,23.507805
3,48,2,150,100,1,1,0,0,1,1,28.710479
4,47,1,100,60,1,1,0,0,0,0,23.011177

### 19. Normalize or scale numerical columns

In [20]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
num_cols = ['age','ap_hi','ap_lo','bmi']
df[num_cols] = scaler.fit_transform(df[num_cols])
df.head()

,age,gender,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,bmi
0,-0.417890,2,-0.997906,-0.133225,1,1,0,0,1,0,-1.044278
1,0.320819,1,0.797892,0.912060,3,1,0,0,1,1,1.420874
2,-0.270148,1,0.199293,-1.178511,3,1,0,0,0,1,-0.751234
3,-0.713373,2,1.396492,1.957346,1,1,0,0,1,1,0.238337
4,-0.861115,1,-1.596506,-2.223797,1,1,0,0,0,0,-0.845694

### 20. Checking for imbalaced

In [21]:
df['cardio'].value_counts(normalize=True)

cardio
0    0.505287
1    0.494713
Name: proportion, dtype: float64

### 21. save file

In [ ]:
df.to_csv('cleaned_cardio.csv', index=False)